import type { Metadata } from "next";
import { Bebas_Neue, Manrope } from "next/font/google";
import Header from "./organisms/Header";
import "./globals.css";

const bebas = Bebas_Neue({
  weight: "400", // Only one weight available
  subsets: ["latin"],
  variable: "--font-bebas",
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bebas.variable} ${manrope.variable} antialiased`}>
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
