import type { Metadata } from "next";
import { Bebas_Neue, Manrope } from "next/font/google";
import Header from "./components/organisms/Header";
import "./globals.css";
import Section from "./components/Section";

const bebas = Bebas_Neue({
  weight: "400", // Only one weight available
  subsets: ["latin"],
  variable: "--font-bebas",
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bebas.variable} ${manrope.variable} antialiased bg-gradient-to-r from-blue to-purple`}
      >
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
